services:
  postgres:
    container_name: postgres_fiber
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app
  
  app:
    container_name: app_go
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    networks:
      - app
    environment:
      - DATABASE_URL=postgres://postgres:my_pass@postgres_fiber:5432/postgres?sslmode=disable
      - LOG_FORMAT=json
      - LOG_LEVEL=1
    restart: on-failure
networks:
  app: