// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type SubmitButtonProps struct {
	Text string
}

func SubmitButton(props SubmitButtonProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = SubmitButtonStyle().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<button class=\"submit-btn\" type=\"submit\"><span class=\"submit-btn__text\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(props.Text)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/submit-button.templ`, Line: 10, Col: 45}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span><div class=\"submit-btn__loader\"></div></button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func SubmitButtonStyle() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<style>\r\n\t.submit-btn {\r\n\t\tdisplay: flex;\r\n\t\tjustify-content: center;\r\n\t\talign-items: center;\r\n\t\twidth: 283px;\r\n\t\theight: 80px;\r\n\t\tpadding-top: 14px;\r\n\t\tpadding-right: 28px;\r\n\t\tpadding-bottom: 14px;\r\n\t\tpadding-left: 28px;\r\n\t\tgap: 10px;\r\n\t\tborder-radius: 20px;\r\n\t\tborder: none;\r\n\t\ttransition: 200ms;\r\n\t\tbackground: #309689;\r\n\t\tfont-weight: 600;\r\n\t\tfont-size: 18px;\r\n\t\tcolor: #FFFFFF;\r\n\t\tcursor: pointer;\r\n\t}\r\n\t.submit-btn:hover {\r\n\t\tbackground: #21665d;\r\n\t}\r\n\r\n\t.submit-btn__text {\r\n\t\tdisplay: flex;\r\n\t\tjustify-content: center;\r\n\t}\r\n\r\n\t.htmx-request .submit-btn__text {\r\n\t\tdisplay: none;\r\n\t}\r\n\r\n\t/* HTML: <div class=\"loader\"></div> */\r\n\t.submit-btn__loader {\r\n\t\tdisplay: none;\r\n\t}\r\n\t.htmx-request .submit-btn__loader {\r\n\t\tdisplay: block;\r\n\t\twidth: 50px;\r\n\t\taspect-ratio: 1;\r\n\t\tdisplay: grid;\r\n\t\tborder: 4px solid #0000;\r\n\t\tborder-radius: 50%;\r\n\t\tborder-right-color: #25b09b;\r\n\t\tanimation: l15 1s infinite linear;\r\n\t}\r\n\t.submit-btn__loader::before,\r\n\t.submit-btn__loader::after {    \r\n\t\tcontent: \"\";\r\n\t\tgrid-area: 1/1;\r\n\t\tmargin: 2px;\r\n\t\tborder: inherit;\r\n\t\tborder-radius: 50%;\r\n\t\tanimation: l15 2s infinite;\r\n\t}\r\n\t.submit-btn__loader::after {\r\n\t\tmargin: 8px;\r\n\t\tanimation-duration: 3s;\r\n\t}\r\n\t@keyframes l15{ \r\n\t\t100%{transform: rotate(1turn)}\r\n\t}\r\n\t</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
