CREATE TABLE news.news (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    preview VARCHAR(255) NOT NULL,
    text VARCHAR(255) NOT NULL,
    user_id INT NOT NULL,
    user_email VARCHAR(255) NOT NULL,
    categories VARCHAR(255) NOT NULL,
    keywords VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);