// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "ostkost/go-ps-fiber/views/components"

func Menu() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = MenuStyle().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"menu\"><div class=\"menu__logo\"><img class=\"menu__svg\" src=\"/public/images/logo.svg\" alt=\"logo\"> <span>Моя работа</span></div><div class=\"menu__links\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.LinkButton(components.LinkButtonProps{Text: "Войти", Href: "#"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.LinkButton(components.LinkButtonProps{Text: "Зарегистрироваться", Href: "/register"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<a href=\"#\" class=\"menu__register\">Зарегистрироваться</a></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func MenuStyle() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<style>\r\n        .menu {\r\n            display: flex;\r\n            justify-content: space-between;\r\n            width: 100%;\r\n            height: 80px;\r\n            padding: 20px 77px;\r\n\r\n        }\r\n        .menu__logo {\r\n            display: flex;\r\n            justify-content: flex-start;\r\n            gap: 10px;\r\n            font-style: normal;\r\n            font-weight: 600;\r\n            font-size: 20px;\r\n            line-height: 27px;\r\n            color: #FFFFFF;\r\n        }\r\n         .menu__svg {\r\n            height: 25px;\r\n            width: 25px;\r\n        }\r\n        .menu__links {\r\n            display: flex;\r\n        }\r\n        .menu__login {\r\n            display: flex;\r\n            justify-content: center;\r\n            align-items: center;\r\n            height: 40px;\r\n            padding: 14px 20px;\r\n            border-radius: 8px;\r\n            font-size: 16px;\r\n            line-height: 22px;\r\n            color: #FFFFFF;\r\n            text-decoration: none;\r\n            transition: 200ms;\r\n        }\r\n         .menu__login:hover {\r\n            background: #adadad;\r\n        }\r\n        .menu__register {\r\n            display: flex;\r\n            justify-content: center;\r\n            align-items: center;\r\n            padding: 14px 20px;\r\n            width: 208px;\r\n            height: 40px;\r\n            border-radius: 8px;\r\n            background: #309689;\r\n            color: #FFFFFF;\r\n            text-decoration: none;\r\n            transition: 200ms;\r\n        }\r\n        .menu__register:hover {\r\n            background: #21665d;\r\n        }\r\n    </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
